#!/usr/bin/env python3
"""
Concatenate shared JS files into a single C string literal, stripping ES module
import/export syntax so the result can be evaluated by an embedded JS engine
(QuickJS) without a module loader.

Usage: gen_js_bundle.py math.js displayPlacement.js > display_placement_bundle.h
"""

import sys
import re

def strip_esm(text):
    lines = []
    for line in text.split('\n'):
        # Drop ES module import lines
        if re.match(r'^\s*import\s+', line):
            continue
        # Strip 'export' keyword prefix from declarations
        line = re.sub(r'^export\s+', '', line)
        lines.append(line)
    return '\n'.join(lines)

def c_escape(line):
    line = line.replace('\\', '\\\\')
    line = line.replace('"', '\\"')
    return line

def main():
    if len(sys.argv) < 2:
        print("Usage: gen_js_bundle.py file1.js [file2.js ...] > output.h", file=sys.stderr)
        sys.exit(1)

    print("/* AUTO-GENERATED by tools/gen_js_bundle.py — do not edit */")
    print("#pragma GCC diagnostic push")
    print('#pragma GCC diagnostic ignored "-Woverlength-strings"')
    print("static const char k_display_placement_js[] =")

    for path in sys.argv[1:]:
        with open(path) as f:
            text = f.read()
        text = strip_esm(text)
        for line in text.split('\n'):
            print(f'    "{c_escape(line)}\\n"')

    print(";")
    print("#pragma GCC diagnostic pop")

if __name__ == '__main__':
    main()
